---
- name: download Tomcat
  local_action: >
    get_url
      url="http://ftp.unicamp.br/pub/apache/tomcat/tomcat-7/v{{tomcat_version}}/bin/{{tomcat_package}}"
      dest="{{download_dir}}/{{tomcat_package}}"

- name: ensures {{tomcat_dir}} exists
  file:
    path="{{tomcat_dir}}"
    state=directory

- name: unpack Tomcat
  unarchive:
    src="{{download_dir}}/{{tomcat_package}}"
    dest="{{tomcat_dir}}"
    creates="{{tomcat_dir}}/{{tomcat_version}}/bin/startup.sh"
  tags: unpack

- name: ensures Tomcat context config folder exists
  file:
    path="{{tomcat_dir}}/{{tomcat_version}}/conf/Catalina/localhost"
    state=directory

- name: configures server.xml
  template:
    src=server.xml.j2
    dest="{{tomcat_dir}}/{{tomcat_version}}/conf/server.xml"

- name: configures tomcat-users.xml
  template:
    src="tomcat-users.xml.j2"
    dest="{{tomcat_dir}}/{{tomcat_version}}/conf/tomcat-users.xml"

- name: configures logging.properties
  template:
    src="logging.properties.j2"
    dest="{{tomcat_dir}}/{{tomcat_version}}/conf/logging.properties"

- name: creates tomcat.sh
  template:
    src="tomcat.sh.j2"
    dest="{{tomcat_dir}}/{{tomcat_version}}/tomcat.sh"
    mode=0700

- name: configures the setenv.sh script
  template:
    src=setenv.sh.j2
    dest="{{tomcat_dir}}/{{tomcat_version}}/bin/setenv.sh"
    mode=0755

#- include: multiInstances.yml
#  when: tomcat.instances is defined

#- include: singleInstance.yml
#  when: tomcat.instances is not defined