---
- name: download Tomcat
  local_action: >
    get_url
      url="http://ftp.unicamp.br/pub/apache/tomcat/tomcat-7/v{{tomcat.version}}/bin/{{tomcat.package}}"
      dest="{{roles.downloadDir}}/{{tomcat.package}}"

- name: ensures {{tomcat.dir}} exists
  file:
    path="{{tomcat.dir}}"
    state=directory

- name: unpack Tomcat
  unarchive:
    src="{{roles.downloadDir}}/{{tomcat.package}}"
    dest="{{tomcat.dir}}"
    creates="{{tomcat.dir}}/{{tomcat.dist}}"

- name: ensures Tomcat context config folder exists
  file:
    path="{{tomcat.dir}}/{{tomcat.dist}}/conf/Catalina/localhost"
    state=directory

- name: configures server.xml
  template:
    src=server.xml.j2
    dest="{{tomcat.dir}}/{{tomcat.dist}}/conf/server.xml"

- name: configures tomcat-users.xml
  template:
    src="tomcat-users.xml.j2"
    dest="{{tomcat.dir}}/{{tomcat.dist}}/conf/tomcat-users.xml"

- name: configures the setenv.sh script
  template:
    src=setenv.sh.j2
    dest="{{tomcat.dir}}/{{tomcat.dist}}/bin/setenv.sh"
    mode=0755

#- include: multiInstances.yml
#  when: tomcat.instances is defined

#- include: singleInstance.yml
#  when: tomcat.instances is not defined