---

- name: ensures {{solr_dir}}/{{item[0]}}/{{item[1]}} exists
  file: 
    path="{{solr_dir}}/{{item[0]}}/{{item[1]}}"
    state=directory
    mode=0700
  with_nested:
    - solr_core_names
    - [ 'data', 'conf' ]

- name: copies config files to {{solr_dir}}/{{item}}/conf
  copy:
    src="{{solr_local_home}}/{{item}}/conf/"
    dest="{{solr_dir}}/{{item}}/conf/"
    mode=0600
  with_items: solr_core_names