---

- name: download Solr to hosts
  local_action: >
    get_url 
      url="https://archive.apache.org/dist/lucene/solr/{{solr_version}}/{{solr_package}}" 
      dest="{{download_dir}}/{{solr_package}}"

- name: unpack Solr to host
  local_action: >
    unarchive
      src="{{download_dir}}/{{solr_package}}"
      dest="{{download_dir}}/"
      creates="{{download_dir}}/{{solr_dist}}"

- name: ensures {{item}} directory exists
  file: path={{item}} state=directory
  with_items:
    - "{{solr_dir}}/lib"

- name: copies solr.war to {{solr_dir}}
  copy:
    src="{{download_dir}}/{{solr_dist}}/example/webapps/solr.war"
    dest="{{solr_dir}}"

- name: solr.xml
  template:
    src="solr.xml.j2"
    dest="{{solr_dir}}/solr.xml"

- name: ensures all needed Solr dist packages are present
  copy:
    src="{{download_dir}}/{{solr_dist}}/dist/{{item}}"
    dest="{{solr_dir}}/lib/"
  with_items:
  - "solr-dataimporthandler-{{solr_version}}.jar"

- include: coreConfig.yml

- include: tomcat7.yml
  when: solr_container == 'tomcat7'
  tags: tomcat