---
- name: download Oracle JDK7 to host {{roles.downloadDir}}
  local_action: >
    command wget -N -P "{{roles.downloadDir}}" --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz
    creates="{{roles.downloadDir}}/jdk-7u51-linux-x64.tar.gz"

- name: "{{java.dir}} must exist"
  file: path={{java.dir}} state=directory

- name: unpack Jdk7
  unarchive: 
    src="jdk-7u51-linux-x64.tar.gz"
    dest="{{java.dir}}"
    creates="{{java.dir}}/{{java.dist}}"

- name: setup JAVA_HOME
  lineinfile:
    dest=~/.bashrc
    line="export JAVA_HOME={{java.dir}}/jdk1.7.0_51"
    state=present
    insertafter=EOF
    create=true

- name: append JAVA_HOME to PATH
  lineinfile:
    dest=~/.bashrc
    line="export PATH=$JAVA_HOME/bin:$PATH"
    state=present
    insertafter=EOF
    create=true
